name: build-and-deploy


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Clone subrepos
        run: |
          mkdir -p source/doc
          cd source/doc
          git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@github.com/Duatic/dynaarm_demo.git
          git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@github.com/Duatic/dynaarm_description.git
          git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@github.com/Duatic/dynaarm_driver.git
      - name: Build static files
        id: build
        run: |
          make html
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: build/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        if: ${{ success() && github.event_name != 'pull_request' && !env.ACT }}
        id: deployment
        uses: actions/deploy-pages@v4
